### ISSUE TITLE
Error when installing on Mac ARM chip.

### ISSUE THREAD

**Issue by oiclid** [lgalabru/clarinet#19]
I get the following error when I try to install on Mac ARM chip:

> error[E0433]: failed to resolve: use of undeclared crate or module `base64`
   --> /Users/zerodiv/.cargo/registry/src/github.com-1ecc6299db9ec823/ron-0.6.4/src/de/mod.rs:318:13
    |
318 |             base64::decode(base64_str)
    |             ^^^^^^ use of undeclared crate or module `base64`

>error[E0433]: failed to resolve: use of undeclared crate or module `base64`
   --> /Users/zerodiv/.cargo/registry/src/github.com-1ecc6299db9ec823/ron-0.6.4/src/ser/mod.rs:436:28
    |
436 |         self.serialize_str(base64::encode(v).as_str())
    |                            ^^^^^^ use of undeclared crate or module `base64`

>error[E0433]: failed to resolve: use of undeclared crate or module `base64`
  --> /Users/zerodiv/.cargo/registry/src/github.com-1ecc6299db9ec823/ron-0.6.4/src/error.rs:20:17
   |
20 |     Base64Error(base64::DecodeError),
   |                 ^^^^^^ use of undeclared crate or module `base64`

>error: aborting due to 3 previous errors

>For more information about this error, try `rustc --explain E0433`.
error: could not compile `ron`

>To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `clarinet v0.7.1`, intermediate artifacts can be found at `/var/folders/c7/5x1prqfj4vngt57pzh7tdb440000gn/T/cargo-install8elSA1`

>Caused by:
  build failed

**Comment by lgalabru** [comment]
This project is being developed on a Apple M1, I don't think that the issue you experiencing is coming from the architecture.
I'd look into the cargo setup instead.
